#!/bin/bash

source functions

readonly CMD=../bin/edfsay
export RESOURCE_DIR=../etc/edfsay

start_test edfsay

assert_exec_ok "ヘルプメッセージが出力できる(-h)" $CMD -h
assert_exec_ok "ヘルプメッセージが出力できる(--help)" $CMD --help
assert_exec_ok "バージョン情報が出力できる(-v)" $CMD -v
assert_exec_ok "バージョン情報が出力できる(--version)" $CMD --version
assert_exec_ok "chatサブコマンドを呼び出せる" $CMD chat
assert_exec_ok "commlogサブコマンドを呼び出せる" $CMD commlog
assert_exec_ng "存在しないサブコマンドを指定したときは異常出力する" $CMD hoge

end_test
